### ISSUE TITLE
Support cross compiling to ARM

### ISSUE THREAD

**Issue by julienw** [fxbox/openzwave-rust#25]
Maybe this already work, but I doubt it :)

**Comment by fabricedesre** [comment]
I'm able to build using the docker image at https://hub.docker.com/r/fabricedesre/foxbox-armhf/ (the Dockerfile is at https://github.com/fabricedesre/rustpi2)

To build, go to the foxbox directory and do:
docker run --name rustpi2_run -v `pwd`:/home/user/dev/source -v $HOME/.cargo:/home/user/.cargo fabricedesre/foxbox-armhf cargopi build

So far so good... but once you try to run it on the RPi, we fail with:

[2016-04-13 17:29:25.010](29664) INFO  nUPNP server: Starting registration with http://knilxof.org:4242/register
[2016-04-13 17:29:25.011](29664) INFO  Got ip address: 10.252.26.242
[2016-04-13 17:29:25.014](29666) INFO  Loaded certificates from directory: "certs/"
[2016-04-13 17:29:25.015](29666) INFO  Generating new self-signed cert for foxbox.local
[2016-04-13 17:29:25.224](29664) INFO  UPnP search for devices matching "urn:cellvision:service:Null:1" (0)
[2016-04-13 17:29:25.227](29676) INFO  UPnP search for devices matching "ssdp:all" (0)
[2016-04-13 17:29:25.232](29690) INFO  Started Thinkerbell main thread.
2016-04-13 17:29:25.233 Error, Cannot find a path to the configuration files at /home/user/.cargo/git/checkouts/openzwave-rust-3fdf6c635691fa96/master/openzwave-sys/open-zwave/config/. Exiting...
2016-04-13 17:29:25.234 Error, Exception: Options.cpp:91 - 1 - Cannot Find Configuration Files
Error: Options.cpp:91 - Cannot Find Configuration Files

I haven't checked the library to see how we can fix that, but for sure we need to change where the library expects the config files to be.

**Comment by fabricedesre** [comment]
we looked at that with @dhylands and found a solution: shipping the config/ directory at the root of the foxbox directory (like our static/ assets) works!

**Comment by julienw** [comment]
In https://github.com/fxbox/openzwave-adapter/wiki#configuration-paths-and-deployment I said you can put everything in /etc/openzwave/ (I think it's cleaner). But having it in the config/ directory work for me too !

**Comment by fabricedesre** [comment]
Putting config files under /etc/openzwave makes it harder to do a self contained tarball though. What I would like is to use an environmental variable. Do we build with SYSCONFDIR defined? (see https://github.com/fxbox/open-zwave/blob/f64ac263249b094acf231eeac6dc69a3caa40087/cpp/src/Options.cpp#L83)

**Comment by dhylands** [comment]
open-zwave's cpp/build/Makefile seems to set SYSCONFDIR to /etc/openzwave

If I run strings target/debug/foxbox | grep etc/openzwave then I get the following output:

```
2008 >strings foxbox | grep etc/openzwave
Cannot find a path to the configuration files at %s, Using /etc/openzwave/ instead...
/usr/local/etc/openzwave/
```

which suggests that SYSCONFDIR is set to /etc/openzwave

**Comment by julienw** [comment]
No, `/etc/openzwave` is the last resort, _after_ SYSCONFDIR.

I tried using SYSCONFDIR as a first try but I found that it's used only if `config/` is not found (as `config/` is tried first). I thought it would be misleading if the only fact that a "config" directory is present changes how the program behaves. We can still use it if you want (and actually you can just set it in your build environment, just like you do for CROSS_COMPILE).

**Comment by dhylands** [comment]
Well that would only be the case if SYSCONFDIR is set to something other than /etc/openzwave (which is the default). If you build with PREFIX set, then it will use /PREFIX/etc/openzwave, but as far as I know we don't set PREFIX.
https://github.com/OpenZWave/open-zwave/blob/master/cpp/build/Makefile#L16

**Comment by julienw** [comment]
I totally missed this line, thanks Dave. And I totally confused env variables with defines too. Grr.

And to top it all I was wrong in my comment, saying it by memory.

https://github.com/OpenZWave/open-zwave/blob/master/cpp/src/Options.cpp#L71-L93 is the full code. So ater all we see SYSCONFDIR is used as a last resort, after the configured config path, ./config and /etc/openzwave/.

I think the best way would be to define it somewhere in foxbox and we can pass it from the adapter: at https://github.com/fxbox/openzwave-adapter/blob/master/src/lib.rs#L302 we can use a `ConfigPath::Custom(&str)`.
